name:
  chocolateorange

url:
  https://chocolateorange.github.io

permalink:
  pretty

timezone:
  Asia/Tokyo

future:
  true

sass:
  style:
    compressed

plugins:
  - jekyll-feed
  - jekyll-gist
# - jekyll-github-metadata
# - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
# - jekyll-titles-from-headings
  - jemoji

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - Makefile
  - README.md
  - javascript
  - local_modules
  - node_modules
  - npm_scripts
  - package-lock.json
  - package.json
  - sources
  - vendor
  - webpack.config.js

collections:
  amp:
    permalink:
      /amp/:year/:month/:day/:title/
    output:
      true

defaults:
  - scope:
      path:
        '_amp'
      type:
        'amp'
    values:
      layout:
        'amp'
  - scope:
      path:
        ''
      type:
        'posts'
    values:
      layout:
        'note'

author:
  sasaplus1

twitter:
  username:
    sasaplus1

lang:
  ja_JP

logo:
  /images/icon_144x144.png

social:
  name:
    sasaplus1
  links:
    - https://twitter.com/sasaplus1
    - https://github.com/sasaplus1

repository:
  https://github.com/chocolateorange/chocolateorange.github.io
